export const UPDATE_FORM_DATA_STUDIO_POST = "UPDATE_FORM_DATA_STUDIO_POST";
export const UPDATE_FORM_DATA_STUDIO_ROOM = "UPDATE_FORM_DATA_STUDIO_ROOM";
export const RESET_FORM_DATA = "RESET_FORM_DATA";
