"use client";
import MainLayout from "@/components/layout/layout";
import "./globals.css";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#e22828",
            },
            components: {
              Tabs: {
                colorPrimary: "#e22828",
              },
              Input: {
                borderRadius: "6px",
              },
            },
          }}
        >
          <MainLayout>{children} </MainLayout>
        </ConfigProvider>
      </body>
    </html>
  );
}
