"use client";
import MainLayout from "@/components/layout/MainLayout";
import { ConfigProvider } from "antd";
import { Nunito } from "next/font/google";
import "./globals.scss";
import HookupProvider from "@/components/HookupProvider";
import store from "@/store/store";
import { Provider } from "react-redux";

const nunito = Nunito({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={nunito.className}>
          <HookupProvider>
            <ConfigProvider
              theme={{
                token: {
                  // Seed Token
                  colorPrimary: "#e22828",
                },
                components: {
                  Tabs: {
                    colorPrimary: "#e22828",
                  },
                  Input: {
                    borderRadius: "6px",
                  },
                },
              }}
            >
              <>{children} </>
            </ConfigProvider>
          </HookupProvider>
        </body>
      </html>
    </Provider>
  );
}
