"use client";
import MainLayout from "@/components/layout/layout";
import { ConfigProvider } from "antd";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ConfigProvider
          theme={{
            token: {
              // Seed Token
              colorPrimary: "#e22828",
            },
            components: {
              Tabs: {
                colorPrimary: "#e22828",
              },
              Input: {
                borderRadius: "6px",
              },
            },
          }}
        >
          <MainLayout>{children} </MainLayout>
        </ConfigProvider>
      </body>
    </html>
  );
}
